//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QLDKHP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDangKiHPEntities : DbContext
    {
        public QLDangKiHPEntities()
            : base("name=QLDangKiHPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccount> tbAccounts { get; set; }
        public virtual DbSet<tbChiTietPDK> tbChiTietPDKs { get; set; }
        public virtual DbSet<tbDiem> tbDiems { get; set; }
        public virtual DbSet<tbKhoa> tbKhoas { get; set; }
        public virtual DbSet<tbMonHoc> tbMonHocs { get; set; }
        public virtual DbSet<tbPhieuDangKy> tbPhieuDangKies { get; set; }
        public virtual DbSet<tbSinhVien> tbSinhViens { get; set; }
    }
}
