//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QLDKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDiem
    {
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> DiemKiemTraTrongLop { get; set; }
        public Nullable<double> DiemGiuaKy { get; set; }
        public Nullable<double> DiemCuoiKy { get; set; }
    
        public virtual tbMonHoc tbMonHoc { get; set; }
        public virtual tbSinhVien tbSinhVien { get; set; }
    }
}
