//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QLDKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbKhoa()
        {
            this.tbSinhViens = new HashSet<tbSinhVien>();
            this.tbMonHocs = new HashSet<tbMonHoc>();
        }
    
        public string MaKhoa { get; set; }
        public string TenKhoa { get; set; }
        public string DiaDiemVanPhong { get; set; }
        public string SoDienThoaiLienLac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSinhVien> tbSinhViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMonHoc> tbMonHocs { get; set; }
    }
}
