//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QLDKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhieuDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhieuDangKy()
        {
            this.tbChiTietPDKs = new HashSet<tbChiTietPDK>();
        }
    
        public string SoPDK { get; set; }
        public string MaSV { get; set; }
        public string TenKhoa { get; set; }
        public string HocKi { get; set; }
        public string TongSoTC { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChiTietPDK> tbChiTietPDKs { get; set; }
        public virtual tbSinhVien tbSinhVien { get; set; }
    }
}
